//! eBPF program loader, lifecycle management, and ring buffer consumer.
//!
//! [`EbpfRuntime`] is the main entry point: it loads the compiled BPF
//! skeleton, attaches tracepoints, and spawns a blocking reader thread
//! that forwards decoded events into a `tokio::mpsc` channel.

use super::events::{self, RuntimeEvent};
use super::metrics::EbpfMetrics;
use anyhow::{Context, Result};
use libbpf_rs::MapCore;
use libbpf_rs::skel::{OpenSkel, Skel, SkelBuilder};
use std::mem::MaybeUninit;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use tokio::sync::mpsc;

// SAFETY: This module is auto-generated by libbpf-cargo from prxsd.bpf.c.
// All unsafe code within is the standard BPF skeleton loader pattern
// (mmap, ioctl to the kernel BPF subsystem). The generated code is
// trusted as part of the build pipeline.
#[allow(
    clippy::pedantic,
    clippy::nursery,
    clippy::all,
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code,
    unsafe_code
)]
mod skel {
    include!(concat!(env!("OUT_DIR"), "/prxsd.skel.rs"));
}

use skel::PrxsdSkelBuilder;

/// Check whether the current process has the capabilities needed to
/// load and attach BPF programs.
pub fn check_capabilities() -> Result<()> {
    // Read effective capabilities from /proc/self/status.
    let status = std::fs::read_to_string("/proc/self/status").context("failed to read /proc/self/status")?;

    for line in status.lines() {
        if let Some(hex) = line.strip_prefix("CapEff:\t") {
            let caps = u64::from_str_radix(hex.trim(), 16).context("failed to parse CapEff")?;

            // CAP_BPF = 39, CAP_PERFMON = 38, CAP_SYS_ADMIN = 21
            let cap_bpf = 1u64 << 39;
            let cap_perfmon = 1u64 << 38;
            let cap_sys_admin = 1u64 << 21;

            if caps & cap_sys_admin != 0 {
                // CAP_SYS_ADMIN implies everything we need.
                return Ok(());
            }

            if caps & cap_bpf == 0 {
                anyhow::bail!(
                    "missing CAP_BPF capability. Run with sudo or use: \
                     sudo setcap cap_bpf,cap_perfmon+ep <binary>"
                );
            }
            if caps & cap_perfmon == 0 {
                anyhow::bail!(
                    "missing CAP_PERFMON capability. Run with sudo or use: \
                     sudo setcap cap_bpf,cap_perfmon+ep <binary>"
                );
            }

            return Ok(());
        }
    }

    anyhow::bail!("could not find CapEff in /proc/self/status");
}

/// The main eBPF runtime that manages BPF program lifecycle and event
/// delivery.
pub struct EbpfRuntime {
    /// Shared flag to signal the reader thread to stop.
    running: Arc<AtomicBool>,
    /// Handle to the blocking reader thread.
    reader_handle: Option<std::thread::JoinHandle<()>>,
    /// Metrics shared with the reader thread.
    metrics: Arc<EbpfMetrics>,
}

impl EbpfRuntime {
    /// Load the BPF skeleton, attach all tracepoints, and start the
    /// ring buffer consumer thread.
    ///
    /// Events are sent to the returned `mpsc::Receiver`.
    ///
    /// # Errors
    ///
    /// Returns an error if capability checks fail, BPF loading fails,
    /// or tracepoint attachment fails.
    pub fn start(buffer_size: usize) -> Result<(Self, mpsc::Receiver<RuntimeEvent>)> {
        check_capabilities().context("eBPF capability check failed")?;

        let (tx, rx) = mpsc::channel(buffer_size);
        let running = Arc::new(AtomicBool::new(true));
        let metrics = Arc::new(EbpfMetrics::new());

        let r = Arc::clone(&running);
        let m = Arc::clone(&metrics);

        let reader_handle = std::thread::Builder::new()
            .name("ebpf-reader".into())
            .spawn(move || {
                if let Err(e) = run_reader(r, tx, m) {
                    tracing::error!("eBPF reader thread exited with error: {e:#}");
                }
            })
            .context("failed to spawn eBPF reader thread")?;

        Ok((
            Self {
                running,
                reader_handle: Some(reader_handle),
                metrics,
            },
            rx,
        ))
    }

    /// Get a reference to the shared metrics.
    pub fn metrics(&self) -> &Arc<EbpfMetrics> {
        &self.metrics
    }

    /// Signal the runtime to stop and wait for the reader thread.
    pub fn stop(&mut self) {
        self.running.store(false, Ordering::Release);
        if let Some(h) = self.reader_handle.take() {
            let _ = h.join();
        }
    }
}

impl Drop for EbpfRuntime {
    fn drop(&mut self) {
        self.stop();
    }
}

/// The blocking reader thread: load BPF, attach, poll ring buffer.
fn run_reader(running: Arc<AtomicBool>, tx: mpsc::Sender<RuntimeEvent>, metrics: Arc<EbpfMetrics>) -> Result<()> {
    tracing::info!("loading eBPF skeleton...");

    let builder = PrxsdSkelBuilder::default();
    let mut open_object = MaybeUninit::uninit();
    let open_skel = builder.open(&mut open_object).context("failed to open BPF skeleton")?;
    let mut skel = open_skel.load().context("failed to load BPF programs")?;

    tracing::info!("attaching eBPF tracepoints...");
    skel.attach().context("failed to attach BPF tracepoints")?;
    tracing::info!("eBPF tracepoints attached successfully");

    // Set up ring buffer with callback.
    let metrics_cb = Arc::clone(&metrics);
    let tx_cb = tx.clone();

    let mut ring_builder = libbpf_rs::RingBufferBuilder::new();
    ring_builder
        .add(&skel.maps.events, move |data: &[u8]| {
            match events::decode_event(data) {
                Some(event) => {
                    metrics_cb.inc_event(event.kind);
                    match tx_cb.try_send(event) {
                        Ok(()) => {}
                        Err(tokio::sync::mpsc::error::TrySendError::Full(_)) => {
                            // Channel full — drop the event and record it.
                            metrics_cb.inc_dropped();
                            tracing::trace!("eBPF event dropped (channel full)");
                        }
                        Err(tokio::sync::mpsc::error::TrySendError::Closed(_)) => {
                            // Receiver dropped — we should stop.
                            return 1;
                        }
                    }
                }
                None => {
                    metrics_cb.inc_decode_error();
                    tracing::trace!("failed to decode BPF event ({} bytes)", data.len());
                }
            }
            0
        })
        .context("failed to add ring buffer callback")?;

    let ring = ring_builder.build().context("failed to build ring buffer")?;

    tracing::info!("eBPF ring buffer consumer started");

    let mut poll_count: u64 = 0;

    while running.load(Ordering::Acquire) {
        // Poll with 100ms timeout so we can check the running flag.
        match ring.poll(std::time::Duration::from_millis(100)) {
            Ok(_) => {}
            Err(e) => {
                metrics.inc_poll_error();
                // EINTR is normal on signal delivery.
                let is_eintr = e.kind() == libbpf_rs::ErrorKind::Interrupted;
                if !is_eintr {
                    tracing::warn!("ring buffer poll error: {e}");
                }
            }
        }

        // Read kernel-side BPF drop counter every ~10 seconds (100 polls × 100ms).
        poll_count = poll_count.wrapping_add(1);
        if poll_count % 100 == 0 {
            if let Some(drops) = read_bpf_drops(&skel.maps.drop_cnt) {
                metrics.set_bpf_drops(drops);
            }
        }
    }

    tracing::info!("eBPF reader thread stopping, detaching programs...");
    // BPF programs are automatically detached when `skel` is dropped.
    drop(ring);
    drop(skel);
    tracing::info!("eBPF programs detached");

    Ok(())
}

/// Read the total ring buffer reservation drop count from the BPF per-CPU
/// array map.  Returns `None` on read failure.
fn read_bpf_drops(map: &libbpf_rs::Map) -> Option<u64> {
    let key = 0u32.to_ne_bytes();
    let values = match map.lookup_percpu(&key, libbpf_rs::MapFlags::ANY) {
        Ok(Some(vals)) => vals,
        _ => return None,
    };

    let mut total: u64 = 0;
    for v in &values {
        let bytes: &[u8] = v.as_slice();
        if let Some(slice) = bytes.get(..8) {
            let mut arr = [0u8; 8];
            arr.copy_from_slice(slice);
            total = total.saturating_add(u64::from_ne_bytes(arr));
        }
    }
    Some(total)
}
