# Formula template — actual formula is auto-generated by the release workflow
# and pushed to https://github.com/openprx/homebrew-tap
#
# Install: brew tap openprx/tap && brew install prx-sd

class PrxSd < Formula
  desc "Open-source Rust antivirus engine with YARA-X and real-time protection"
  homepage "https://github.com/openprx/prx-sd"
  version "0.1.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openprx/prx-sd/releases/download/v#{version}/sd-macos-x86_64"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/openprx/prx-sd/releases/download/v#{version}/sd-macos-aarch64"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    url "https://github.com/openprx/prx-sd/releases/download/v#{version}/sd-linux-x86_64"
    sha256 "PLACEHOLDER"
  end

  def install
    bin.install Dir["sd-*"].first => "sd"
  end

  def caveats
    <<~EOS
      PRX-SD installed. Quick start:

        # Scan a file or directory
        sd scan /path/to/check

        # Update virus signatures
        sd update

        # Enable real-time monitoring
        sd monitor /home /tmp
    EOS
  end

  test do
    assert_match "prx-sd", shell_output("#{bin}/sd --version")
  end
end
